version: "3.8"

services:
  postgresdb:
    image: postgres:14
    container_name: todopsql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todonet

  starterapp:
    build:
      context: .
    container_name: tododoo-app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    networks:
      - todonet

networks:
  todonet:
    driver: bridge

volumes:
  postgres_data:
